capstone project module 1
BouaikIlham/First-Capstone-Project pull request #1
Opened 2022-04-18 11:46 UTC by BouaikIlham

2022-04-21 23:26 UTC, gemmen29 requested changes
Hi @BouaikIlham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 23:26 UTC, gemmen29 commented on index.html
> +        </div>
- [x] Kindly try to match the Behance design in the intro section on the home page mobile version by increasing the `font-size` of the heading and work hours

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164563599-3ba70e9b-0a02-4004-9104-ae6453eb1de4.png) | ![image](https://user-images.githubusercontent.com/24703171/164563372-13b37658-4421-4624-83ae-d070bddc84b2.png) |

- [x] and also increase `font-size` in desktop version

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164564157-3c487af5-3851-441f-9b0f-12e2da88fdf5.png) | ![image](https://user-images.githubusercontent.com/24703171/164564247-3d5bb416-bb09-4468-be65-a627aded56bf.png) |

2022-04-21 23:26 UTC, gemmen29 commented on index.html
> +      <section id="sponsor" class="sponsor"></section>
- [ ] Kindly try to match the Behance design in the `featured speakers` section on the home page mobile version by increasing the `image size` of the speaker and making the text start from the beginning.

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164564604-5c2cb312-f324-4bf9-82b6-efc528d7d473.png) | ![image](https://user-images.githubusercontent.com/24703171/164564621-7b40365a-cb19-4769-b158-7bbbdfe01e77.png) |

- [ ] and also the same in desktop version

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164564884-6a805b90-cb41-41d7-acd3-dbb21e81c756.png) | ![image](https://user-images.githubusercontent.com/24703171/164564787-cb5dc47e-84c6-44db-9d32-bf9929f05002.png) |

2022-04-21 23:26 UTC, gemmen29 commented on index.html
> +      </section>
- [ ] Kindly try to match the Behance design in the `partners` section on the home page mobile version by increasing the `image size` of each brand, increasing top spacing, and decreasing button spacing.

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164565133-841dfa58-06fa-4d53-92ef-1c79b7f0ffb5.png) | ![image](https://user-images.githubusercontent.com/24703171/164565160-c593a440-8ce9-4813-b2be-90d84d992d07.png) |

- [ ] and also the same in the desktop version

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164565352-8b3a6a92-c090-4292-a393-ac684a47cdd3.png) | ![image](https://user-images.githubusercontent.com/24703171/164565309-2c92e474-bbf0-4db7-8812-88482c60b86c.png) |

2022-04-21 23:26 UTC, gemmen29 commented on index.html
> +      </div>
- [ ] Kindly try to match the Behance design in the `footer` section on the home page mobile version by increasing the top and bottom spacing and increasing the gap between the logo and text.

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164565767-f5ce2747-5099-4536-b335-442d9ee7c7e7.png) | ![image](https://user-images.githubusercontent.com/24703171/164565706-3cbfcd63-aade-4fff-9001-8852575897a7.png) |

- [ ] and in the desktop version decrease the logo size a little bit.
- [ ] Kindly change the `div` tag to be `footer` tag for semantic purposes.

2022-04-21 23:26 UTC, gemmen29 commented on about.html
> +    </div>
- [ ] Kindly try to match the Behance design in the `footer` section on the about page (same footer as on the home page) 
- [ ] Please make the footer light in the mobile version and dark in the desktop version as in the Behance design.
- mobile version:
![image](https://user-images.githubusercontent.com/24703171/164566283-3d342787-9e21-4d6f-8ddf-b647d64cbbd4.png)
- desktop version:
![image](https://user-images.githubusercontent.com/24703171/164566333-aec9f087-a6b2-49d6-8ac3-edefa6b40480.png)

- [ ] Kindly change the `div` tag to be `footer` tag for semantic purposes.

2022-04-21 23:26 UTC, gemmen29 commented on about.html
> +          <strong><a href="ibouaik@gmail.com">ibouaik@gmail.com</a></strong>
- [ ] Kindly try to match the Behance design in the intro section on the home page mobile version by increasing the `font-size` of the heading and making the text in the center

| Your design | Behance design |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/24703171/164566511-422eaa75-3573-446b-a053-2f1d541f990b.png) | ![image](https://user-images.githubusercontent.com/24703171/164566532-46303f9c-41fc-4d73-86d7-7c918a2437a4.png) |

- [ ] and also the same in the desktop version

2022-04-21 23:26 UTC, gemmen29 commented on README.md
> +
- [OPTIONAL] Please add a screenshot of your project in the README file to make your README more professional.

2022-04-22 09:47 UTC, VICTOR-CHUKWU requested changes
Hi @BouaikIlham , 
## STATUS: REQUIRED CHANGES
Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-22 09:47 UTC, VICTOR-CHUKWU commented on index.html
> +      </section>
- [ ] Your partner section on mobile is overflowing horizontally, I think this is as a result of the CSS style you gave your class `partner-container figure` a width of 200% and also `.partner img` width of 150px, kindly use media query to fix this
![image](https://user-images.githubusercontent.com/66097371/164679824-4cd5883f-bdb8-4362-ba0d-79e977b304eb.png)

2022-04-22 09:47 UTC, VICTOR-CHUKWU commented on about.html
> +    </footer>
- [ ] Just as the previous reviewer mentioned, kindly fix the background colour of your footer, it should be dark on desktop and light on mobile, currently, it is light on all devices, use media query to achieve this
your current design 👇 
   
![image](https://user-images.githubusercontent.com/66097371/164681640-14352a1a-ab43-49ed-b783-7c1407c99bc8.png)

2022-04-22 10:41 UTC, VICTOR-CHUKWU approved these changes
Hi @BouaikIlham ,
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-04-22 10:41 UTC, merged